# radar constraints
MAX_DISTANCE_M = 20
MAX_AZIMUTH_DEGREES = 60

# radar display
DISPLAY_WIDTH = 1250
DISPLAY_HEIGHT = 700
MARGIN = 25
SPACING = 50

# drone node
CIRCLE_RADIUS = 10
ARROW_LENGTH_SF = 25    # px per m/s
ARROW_HEAD_SIZE = 20